"""Mock skills for demo mode — no API key required."""

import time

MOCK_REPORT = """# Security Scan Report

## Executive Summary
The scanned code contains 2 critical vulnerabilities that pose immediate risk of data breach and unauthorised access. Remediation is strongly recommended before deployment.

## Risk Overview
| Severity | Count |
|---|---|
| 🔴 Critical | 2 |
| 🟠 High | 0 |
| 🟡 Medium | 0 |
| 🔵 Low | 0 |
| **Overall Score** | 12 / 100 |

## Findings

### 🔴 Critical — SQL Injection
- **Risk:** Attackers can manipulate database queries to extract, modify, or delete data
- **Location:** Line 1 — `query = "SELECT * FROM users WHERE id = " + user_id`
- **Fix:**
```python
cursor.execute("SELECT * FROM users WHERE id = %s", (user_id,))
```

### 🔴 Critical — Hardcoded API Key
- **Risk:** Secret key exposed in source code is accessible to anyone with repo access
- **Location:** Line 2 — `API_KEY = "sk-1234567890abcdef"`
- **Fix:**
```python
import os
API_KEY = os.getenv("API_KEY")
```

## Recommendations
1. Replace all string-concatenated SQL queries with parameterised statements immediately
2. Rotate the exposed API key — treat it as compromised
3. Move all secrets to environment variables or a secrets manager
4. Add a pre-commit hook to prevent secrets from entering the codebase
5. Run automated SAST scanning as part of your CI/CD pipeline

## Conclusion
Address the two critical findings before any deployment. Both fixes are straightforward and can be applied within the hour.

---
*Generated by CodeGuard AI — Powered by Claude*"""

MOCK_FIX = """## Fixed Code
```python
import os
import sqlite3

# Use environment variable — never hardcode secrets
API_KEY = os.getenv("API_KEY")

def get_user(user_id):
    conn = sqlite3.connect("users.db")
    cursor = conn.cursor()
    # Parameterised query prevents SQL injection
    cursor.execute("SELECT * FROM users WHERE id = ?", (user_id,))
    return cursor.fetchone()
```

## Changes Made
1. **Hardcoded Secret** — Moved `API_KEY` to an environment variable via `os.getenv()`. Never store secrets in source code.
2. **SQL Injection** — Replaced string concatenation with a parameterised query using `?` placeholder. The database driver handles escaping safely.
"""


class MockSecurityReportSkill:
    def generate(self, scan_output: str) -> str:
        time.sleep(1.0)
        return MOCK_REPORT

    def generate_stream(self, scan_output: str):
        for word in MOCK_REPORT.split(" "):
            yield word + " "
            time.sleep(0.015)


class MockAutoFixSkill:
    def fix(self, vulnerable_code: str, vulnerabilities: str, language: str = "auto") -> str:
        time.sleep(1.0)
        return MOCK_FIX

    def fix_stream(self, vulnerable_code: str, vulnerabilities: str, language: str = "auto"):
        for word in MOCK_FIX.split(" "):
            yield word + " "
            time.sleep(0.015)
