"""
SecurityReportSkill — generates a professional, downloadable security report
from a completed vulnerability scan conversation.
"""

from .base import BaseSkill


class SecurityReportSkill(BaseSkill):
    """
    Skill: Security Report Generator

    Input  — raw scan output (Claude's vulnerability analysis)
    Output — a clean, structured markdown security report ready to download
    """

    system_prompt = """You are a professional cybersecurity report writer. \
Your job is to take raw vulnerability scan output and transform it into a clean, \
structured security report suitable for sharing with a development team or manager.

## Report format you must follow exactly

# Security Scan Report

## Executive Summary
(2-3 sentences: what was scanned, how many issues found, overall risk level)

## Risk Overview
| Severity | Count |
|---|---|
| 🔴 Critical | X |
| 🟠 High | X |
| 🟡 Medium | X |
| 🔵 Low | X |
| **Overall Score** | X / 100 |

## Findings

### [Severity] — [Vulnerability Name]
- **Risk:** (one line explanation of the danger)
- **Location:** Line X — `code snippet`
- **Fix:** (concrete fix with code example)

(repeat for each finding)

## Recommendations
(3-5 prioritised action items)

## Conclusion
(1-2 sentences on next steps)

---
*Generated by CodeGuard AI — Powered by Claude*

## Rules
- Be concise and professional — no filler text
- Always include working code in the Fix sections
- Order findings by severity (Critical first)
- Keep the Executive Summary non-technical enough for a manager to understand
"""

    max_tokens = 3000

    def generate(self, scan_output: str) -> str:
        prompt = f"""Transform this vulnerability scan output into a professional security report:

---
{scan_output}
---

Follow the report format exactly. Be concise and professional."""
        return self.run(prompt)

    def generate_stream(self, scan_output: str):
        prompt = f"""Transform this vulnerability scan output into a professional security report:

---
{scan_output}
---

Follow the report format exactly. Be concise and professional."""
        return self.stream(prompt)
